# Generated by Django 5.1 on 2024-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_arthur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='publication_year',
        ),
    ]
